Repository wooriFisa-Final-Project-F4/product-service, pull requests merged in 2023-08, with the labels that each got.

#3 Feature/#1 product register
  src/main/java/f4/product/ProductApplication.java
  src/main/java/f4/product/domain/product/constant/AuctionStatus.java
  src/main/java/f4/product/domain/product/constant/SellStatus.java
  src/main/java/f4/product/domain/product/controller/ProductController.java
  src/main/java/f4/product/domain/product/dto/request/ProductRegisterRequestDto.java
  src/main/java/f4/product/domain/product/persist/entity/Auction.java
  src/main/java/f4/product/domain/product/persist/entity/Product.java
  src/main/java/f4/product/domain/product/persist/repository/AuctionRepository.java
  src/main/java/f4/product/domain/product/persist/repository/ProductRepository.java
  src/main/java/f4/product/domain/product/service/ProductService.java
  src/main/java/f4/product/domain/product/service/ProductServiceImpl.java
  src/main/java/f4/product/global/config/MapperConfig.java
  src/main/java/f4/product/global/constant/CustomErrorCode.java
  src/main/java/f4/product/global/exception/CustomException.java
  src/main/java/f4/product/global/exception/ErrorDetails.java
  src/main/java/f4/product/global/exception/GlobalExceptionHandler.java
Labels: enhancement

#5 #4 save product images
  build.gradle
  src/main/java/f4/product/ProductApplication.java
  src/main/java/f4/product/domain/auction/persist/entity/Auction.java
  src/main/java/f4/product/domain/auction/persist/repository/AuctionRepository.java
  src/main/java/f4/product/domain/product/config/aws/S3Config.java
  src/main/java/f4/product/domain/product/config/aws/S3Service.java
  src/main/java/f4/product/domain/product/config/aws/S3Uploader.java
  src/main/java/f4/product/domain/product/config/aws/exception/EmptyFileException.java
  src/main/java/f4/product/domain/product/config/aws/exception/FileUploadFailureException.java
  src/main/java/f4/product/domain/product/controller/ProductController.java
  src/main/java/f4/product/domain/product/dto/request/ProductRegisterRequestDto.java
  src/main/java/f4/product/domain/product/persist/entity/Product.java
  src/main/java/f4/product/domain/product/service/ProductService.java
  src/main/java/f4/product/domain/product/service/ProductServiceImpl.java
  src/main/java/f4/product/global/constant/CustomErrorCode.java
  src/main/resources/static/index.html
  src/main/resources/static/script.js
Labels: enhancement, help wanted

#9 Fix/#1-s3-upload
  src/main/java/f4/product/ProductApplication.java
  src/main/java/f4/product/constant/AuctionStatus.java
  src/main/java/f4/product/domain/product/constant/AuctionStatus.java
  src/main/java/f4/product/domain/product/controller/ProductController.java
  src/main/java/f4/product/domain/product/dto/request/ProductSaveRequestDto.java
  src/main/java/f4/product/domain/product/persist/entity/Product.java
  src/main/java/f4/product/domain/product/persist/entity/ProductImage.java
  src/main/java/f4/product/domain/product/persist/repository/ProductImageRepository.java
  src/main/java/f4/product/domain/product/persist/repository/ProductRepository.java
  src/main/java/f4/product/domain/product/service/ProductService.java
  src/main/java/f4/product/domain/product/service/impl/ProductServiceImpl.java
  src/main/java/f4/product/global/config/AwsConfig.java
  src/main/java/f4/product/global/constant/CustomErrorCode.java
  src/main/java/f4/product/global/exception/CustomException.java
  src/main/java/f4/product/global/exception/ErrorDetails.java
  src/main/java/f4/product/global/exception/GlobalExceptionHandler.java
  src/main/java/f4/product/global/service/S3Service.java
  src/main/java/f4/product/persist/entity/Product.java
  src/main/java/f4/product/service/ProductService.java
  src/main/java/f4/product/service/impl/ProductServiceImpl.java
  src/test/java/f4/product/service/S3ServiceTest.java
Labels: bug, duplicate, enhancement

#12 Feature/#10 read product
  build.gradle
  src/main/java/f4/product/domain/product/controller/ProductController.java
  src/main/java/f4/product/domain/product/dto/response/ProductReadResponseDto.java
  src/main/java/f4/product/domain/product/persist/repository/ProductRepository.java
  src/main/java/f4/product/domain/product/service/ProductService.java
  src/main/java/f4/product/domain/product/service/impl/ProductServiceImpl.java
  src/main/java/f4/product/global/config/appConfig.java
  src/main/java/f4/product/global/constant/CustomErrorCode.java
Labels: enhancement

#13 [style] 코드 스타일 변경
  src/main/java/f4/product/domain/product/persist/entity/Product.java
  src/main/java/f4/product/domain/product/persist/repository/ProductImageRepository.java
  src/main/java/f4/product/global/config/AppConfig.java
  src/main/java/f4/product/global/config/AwsConfig.java
Labels: duplicate

#14 [#10] [feat] productController
  src/main/java/f4/product/domain/product/controller/ProductController.java
  src/main/java/f4/product/domain/product/dto/request/ProductSaveRequestDto.java
  src/main/java/f4/product/domain/product/dto/response/ProductReadResponseDto.java
  src/main/java/f4/product/domain/product/persist/repository/ProductRepository.java
  src/main/java/f4/product/domain/product/service/ProductService.java
  src/main/java/f4/product/domain/product/service/impl/ProductServiceImpl.java
Labels: duplicate

#15 [refactor] customerror
  src/main/java/f4/product/global/constant/CustomErrorCode.java
  src/main/java/f4/product/global/exception/ErrorDetails.java
  src/main/java/f4/product/global/exception/GlobalExceptionHandler.java
Labels: enhancement

#16 Refactor/product service api
  src/main/java/f4/product/domain/product/controller/ProductController.java
  src/main/java/f4/product/domain/product/dto/request/ProductSaveRequestDto.java
  src/main/java/f4/product/domain/product/dto/response/ProductReadResponseDto.java
  src/main/java/f4/product/domain/product/persist/entity/Product.java
  src/main/java/f4/product/domain/product/service/impl/ProductServiceImpl.java
Labels: enhancement

#18 [#17][feat] 상품 삭제 로직 구현
  src/main/java/f4/product/domain/product/controller/ProductController.java
  src/main/java/f4/product/domain/product/service/ProductService.java
  src/main/java/f4/product/domain/product/service/impl/ProductServiceImpl.java
  src/main/java/f4/product/global/constant/CustomErrorCode.java
  src/main/java/f4/product/global/service/S3Service.java
Labels: enhancement

#19 [#11][feat] 상품 정보 수정 로직 구현
  src/main/java/f4/product/domain/product/controller/ProductController.java
  src/main/java/f4/product/domain/product/dto/request/ProductUpdateRequestDto.java
  src/main/java/f4/product/domain/product/persist/entity/ProductImage.java
  src/main/java/f4/product/domain/product/service/ProductService.java
  src/main/java/f4/product/domain/product/service/impl/ProductServiceImpl.java
Labels: enhancement

#23 Feature/#21 update status
  .gitignore
  build.gradle
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/f4/product/domain/product/controller/ProductController.java
  src/main/java/f4/product/domain/product/dto/response/FeignProductDto.java
  src/main/java/f4/product/domain/product/persist/entity/Product.java
  src/main/java/f4/product/domain/product/persist/repository/ProductRepository.java
  src/main/java/f4/product/domain/product/service/ProductService.java
  src/main/java/f4/product/domain/product/service/impl/ProductServiceImpl.java
  src/main/java/f4/product/global/constant/CustomErrorCode.java
Labels: enhancement

#25 [#24][refactor] 경매 시간이 지났지만 경매상태가 진행중인 상품 수정 로직 수정
  src/main/java/f4/product/domain/product/controller/ProductController.java
  src/main/java/f4/product/domain/product/service/ProductService.java
  src/main/java/f4/product/domain/product/service/impl/ProductServiceImpl.java
Labels: enhancement

#26 [#22][feat] 상품의 상태, 경매시간 조회 로직 구현
  src/main/java/f4/product/domain/product/controller/ProductController.java
  src/main/java/f4/product/domain/product/dto/response/AuctionTimeStatusDto.java
  src/main/java/f4/product/domain/product/service/ProductService.java
  src/main/java/f4/product/domain/product/service/impl/ProductServiceImpl.java
Labels: enhancement
